[package]
name = "mariposa_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
arrow = "54.3.0"
arrow-array = "54.0.0"
arrow-schema = "54.0.0"
chrono = "0.4.31"
log = "0.4.27"
protobuf = "3.3.0"
